id: I9FB55649
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T12:57:18+00:00'
last_modified: '2022-06-16T04:40:18.952963+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2PD17608
  title: 西藏贵族世家 ༡༩༠༠-༡༩༥༡
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    C283:
      image_group_id: I4PD4598
      title: Volume 1 of 西藏贵族世家 1900-1951
      total_pages: 486
      order: 1
      base_file: C283.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
